### ISSUE TITLE
Proximity Sensor not working 

### ISSUE THREAD

**Issue by gs9339** [Umang96/munch_pe_custom_gsi_releases#2]
Proximity Sensor not working. 
![Screenshot_20220814-142019_Sensor Test](https://user-images.githubusercontent.com/110755806/184529574-53e61fa9-72ea-44f3-a232-f202b984f3b0.png)

**Comment by Umang96** [comment]
https://user-images.githubusercontent.com/13455891/184847913-18e7613f-ef23-4b73-b4f9-3a46ec3053fc.mp4

Seems to be working fine, please make sure you install it over correct India firmware.
Also, prefer testing by bringing phone near your ear and not by any other object.

**Comment by gs9339** [comment]
Yes, this started working after sometime. Thank you for your response.
