### ISSUE TITLE
Rear Main Camera Disappeared on K40S

### ISSUE THREAD

**Issue by PeronGH** [Umang96/munch_pe_custom_gsi_releases#3]
I flashed MIUI India on the K40S and installed this ROM, then I noticed that the rear main camera disappeared and the third party Google Camera only works with the front, ultra wide angle and macro lenses. Probably because the K40S has a different rear main camera than the POCO F4.

**Comment by Umang96** [comment]
Yes, looks like k40s has different main cam, can you extract super.img of china rom and flash the extracted vendor.img? Flash it using this -

1. Reboot to FASTBOOTD
2. fastboot flash vendor vendor.img
3. Reboot

**Comment by PeronGH** [comment]
> Yes, looks like k40s has different main cam, can you extract super.img of china rom and flash the extracted vendor.img? Flash it using this -
> 
> 1. Reboot to FASTBOOTD
> 2. fastboot flash vendor vendor.img
> 3. Reboot

I extracted vendor.img from the MIUI China 13.0.10, and flashed it as you instructed. Then K40S fell into boot loop. I also tried to flash super.img from MIUI China 13.0.2 and then flashed the GSI, which also led to boot loop. At last, I got my K40S boot again by flashing the super.img from MIUI India 13.0.3 and then the GSI.

**Comment by Umang96** [comment]
Then I suppose the only solution is to patch India vendor.img and add/replace the camera blobs extraced from China vendor.img, Also, before trying this, please see if just flashing China boot.img fixes something because kernel also has camera drivers.

**Comment by PeronGH** [comment]
The boot.img from MIUI China 13.0.2 caused K40S stuck at booting. Then after flashing boot.img from MIUI China 13.0.10, K40S can boot, but the System UI was not responding and the phone was unusable. I flashed boot.img from MIUI India back and everything returned to normal. I also tried to extract vendor/lib/camera, vendor/lib64/camera and vendor/etc/camera from MIUI China 13.0.10 and made a magisk module containing them. Then K40S can boot and use other cameras, but main camera is still missing.

**Comment by Umang96** [comment]
Kernel drivers are necessary to make camera work, if you patched vendor, kernel is the only remaining issue, maybe test more with 13.0.10 china kernel.

**Comment by PeronGH** [comment]
13.0.10 China kernel will make the system unusable, the system ui will keep crashing. I also tried the stock MIUI India 13.0.3 and MIUI EEA 13.0.6, they both miss the main camera. I think you can make the GSI work with latest MIUI EU which supports both china version and global version of munch.

**Comment by Umang96** [comment]
I will consider that, meanwhile, you can also try Immensity kernel by @UtsavBalar1231, ask him for a build to test.

**Comment by PeronGH** [comment]
I tried Immensity kernel 7.0 for munch with the GSI installed, and K40S did not boot and stuck at the Redmi logo. I also tried to install the GSI on the stock MIUI EEA 13.0.6 and it worked, and then I replaced the boot.img with the one extracted from MIUI China 13.0.6, the phone can boot but the main camera is still missing. I am now trying to patch vendor with libs extracted from MIUI China 13.0.6.

**Comment by PeronGH** [comment]
I made a magisk module containing vendor/lib, vendor/lib64, vendor/etc, and vendor/build.prop and it was still not working. Before installing the module, I flashed the GSI when MIUI EEA 13.0.6 was installed and then replaced boot with the one extracted from MIUI China 13.0.6.

**Comment by PeronGH** [comment]
Actually I don't think the issue matters too much, because apps will use ultra wide camera by default, and ultra wide camera is still OK to scan QR code or take pictures.

**Comment by PeronGH** [comment]
The issue is solved! I flashed a custom firmware which is based on MIUI 13.0.10 and contains the GSI, and everything is working perfectly fine. I found that firmware on a Chinese website called coolapk.
